const LOAD_CAMPUSES = 'LOAD_CAMPUSES';
const CREATE_CAMPUS = 'CREATE_CAMPUS';
const DELETE_CAMPUS = 'DELETE_CAMPUS';
const UPDATE_CAMPUS = 'UPDATE_CAMPUS';
const SELECT_CAMPUS = 'SELECT_CAMPUS';
const SELECT_STUDENT = 'SELECT_STUDENT';
const LOAD_STUDENTS = 'LOAD_STUDENTS';
const CREATE_STUDENT = 'CREATE_STUDENT';
const DELETE_STUDENT = 'DELETE_STUDENT';
const UNREGISTER_STUDENT = 'UNREGISTER_STUDENT';
const UPDATE_STUDENT = 'UPDATE_STUDENT';
const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
const SORT_LAST_NAME = 'SORT_LAST_NAME';

const actionTypes = {
  LOAD_CAMPUSES,
  CREATE_CAMPUS,
  DELETE_CAMPUS,
  UPDATE_CAMPUS,
  SELECT_CAMPUS,
  SELECT_STUDENT,
  LOAD_STUDENTS,
  CREATE_STUDENT,
  DELETE_STUDENT,
  UNREGISTER_STUDENT,
  UPDATE_STUDENT,
  SET_VISIBILITY_FILTER,
  SORT_LAST_NAME,
};

export default actionTypes;
